export const INITIAL_USERS = [
  {
    id: 'dev-admin-001',
    name: 'AgroLink Developer',
    email: 'classicgenius@dev',
    role: 'admin',
    avatar: 'https://ui-avatars.com/api/?name=Dev+Admin&background=1a472a&color=fff',
    joined: 'Jan 2026',
    status: 'active',
    plan: 'business',
    verified: true,
    organicCertified: true,
  },
  {
    id: 'farmer-001',
    name: 'James Asante',
    email: 'james.asante@agrolink.gh',
    role: 'farmer',
    avatar: 'https://ui-avatars.com/api/?name=James+Asante&background=3B823E&color=fff',
    joined: 'Jan 2026',
    phone: '+233 24 123 4567',
    location: 'Ashanti Region',
    status: 'active',
    plan: 'business',
    verified: true,
    organicCertified: true,
    joinedPremiumDate: '2026-01-15',
    premiumRenewalDate: '2026-08-15',
    lastTransactionRef: 'TXN-9011',
  },
  {
    id: 'farmer-002',
    name: 'Brent Farms Ltd.',
    email: 'farmer.brent@agrolink.gh',
    role: 'farmer',
    avatar: 'https://ui-avatars.com/api/?name=Brent+Farms&background=2E7D32&color=fff',
    joined: 'Feb 2026',
    phone: '+233 55 987 6543',
    location: 'Northern Region',
    status: 'active',
    plan: 'starter',
    verified: true,
    organicCertified: false,
    joinedPremiumDate: '2026-02-10',
    premiumRenewalDate: '2026-08-10',
    lastTransactionRef: 'TXN-9012',
  },
  {
    id: 'farmer-003',
    name: 'Kwame Agricultural Enterprise',
    email: 'kwame.farms@accra.gh',
    role: 'farmer',
    avatar: 'https://ui-avatars.com/api/?name=Kwame+Farms&background=1565C0&color=fff',
    joined: 'Feb 2026',
    phone: '+233 20 456 7890',
    location: 'Brong-Ahafo Region',
    status: 'active',
    plan: 'starter',
    verified: false,
    organicCertified: false,
    joinedPremiumDate: '2026-02-17',
    premiumRenewalDate: '2026-08-17',
    lastTransactionRef: 'TXN-9013',
  },
  {
    id: 'buyer-001',
    name: 'Accra Fresh Market',
    email: 'accra.fresh@market.gh',
    role: 'buyer',
    avatar: 'https://ui-avatars.com/api/?name=Accra+Fresh&background=F4C430&color=1C3322',
    joined: 'Feb 2026',
    phone: '+233 27 321 9876',
    location: 'Greater Accra',
    status: 'active',
    plan: 'business',
    verified: true,
    organicCertified: false,
    joinedPremiumDate: '2026-02-20',
    premiumRenewalDate: '2026-08-20',
    lastTransactionRef: 'TXN-9014',
  },
  {
    id: 'buyer-002',
    name: 'Retail Buyers Co.',
    email: 'retail@buyers.gh',
    role: 'buyer',
    avatar: 'https://ui-avatars.com/api/?name=Retail+Buyers&background=7B1FA2&color=fff',
    joined: 'Feb 2026',
    phone: '+233 30 765 4321',
    location: 'Kumasi, Ashanti',
    status: 'active',
    plan: 'free',
    verified: false,
    organicCertified: false,
  },
];
